// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayersService.Models;

#nullable disable

namespace PlayersService.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    [Migration("20220709070748_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlayersService.Models.Players", b =>
                {
                    b.Property<int>("playerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playerid"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<long>("contactnumber")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sportsname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("playerid");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
